---
- hosts: esx_hosts
  gather_facts: false

  tasks:
    - name: Add a Server Hardware to Oneview
      hpe.oneview.oneview_server_hardware:
        hostname: "{{ hostvars.oneview_host.ansible_host }}"
        username: "{{ oneview_username }}"
        password: "{{ oneview_password }}"
        auth_login_domain: "{{ oneview_domain }}"
        api_version: "{{ oneview_apiversion }}"

        state: present
        data:
          hostname : "{{ilo_ip}}"
          username : "admin"
          password : "{{ilo_pw}}"
          force : true
          licensingIntent: "OneView"
          configurationState: "Managed"
      delegate_to: localhost
      ignore_errors: true

    - name: display new server facts
      debug:
        msg: "{{ ansible_facts['server_hardware']['name'] }}"
      ignore_errors: True
      register: display_facts

    # when display facts failed (eg. unreachable hardware) set deploy_status for this hosts to failed
    - name: "set failed fact deploy_status"
      set_fact:
        deploy_status: failed
        cacheable: true
      ignore_unreachable: True
      when: '"FAILED!" in display_facts.msg or "undefined variable" in display_facts.msg'